---ROLE
INSERT INTO "role" (name) VALUES ('POSTULANTE');
INSERT INTO "role" (name) VALUES ('COMISIÓN');
INSERT INTO "role" (name) VALUES ('ADMINISTRADOR DGFM');
INSERT INTO "role" (name) VALUES ('JURIDICA');
INSERT INTO "role" (name) VALUES ('TRANSPARENCIA');
INSERT INTO "role" (name) VALUES ('SUPER ADMINISTRADOR');